src/Entity/Adresse.php
<?php

namespace App\Entity;

use App\Repository\AdresseRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AdresseRepository::class)]
class Adresse
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'adresses')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $adr_uti = null;

    #[ORM\Column(length: 255)]
    private ?string $adr_nom = null;

    #[ORM\Column(length: 255)]
    private ?string $adr_prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $adr_rue = null;

    #[ORM\Column(length: 255)]
    private ?string $adr_code_postal = null;

    #[ORM\Column(length: 255)]
    private ?string $adr_telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $adr_ville = null;

    #[ORM\Column(length: 255)]
    private ?string $adr_pays = null;

    public function __toString(): string
    {
        return $this->adr_nom .' '.$this->adr_prenom .'[-br]'.
        $this->adr_rue .'[-br]'.
        $this->adr_code_postal.' '.$this->adr_ville;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAdrUti(): ?Utilisateur
    {
        return $this->adr_uti;
    }

    public function setAdrUti(?Utilisateur $adr_uti): static
    {
        $this->adr_uti = $adr_uti;

        return $this;
    }

    public function getAdrNom(): ?string
    {
        return $this->adr_nom;
    }

    public function setAdrNom(string $adr_nom): static
    {
        $this->adr_nom = $adr_nom;

        return $this;
    }

    public function getAdrPrenom(): ?string
    {
        return $this->adr_prenom;
    }

    public function setAdrPrenom(string $adr_prenom): static
    {
        $this->adr_prenom = $adr_prenom;

        return $this;
    }

    public function getAdrRue(): ?string
    {
        return $this->adr_rue;
    }

    public function setAdrRue(string $adr_rue): static
    {
        $this->adr_rue = $adr_rue;

        return $this;
    }

    public function getAdrCodePostal(): ?string
    {
        return $this->adr_code_postal;
    }

    public function setAdrCodePostal(string $adr_code_postal): static
    {
        $this->adr_code_postal = $adr_code_postal;

        return $this;
    }

    public function getAdrTelephone(): ?string
    {
        return $this->adr_telephone;
    }

    public function setAdrTelephone(string $adr_telephone): static
    {
        $this->adr_telephone = $adr_telephone;

        return $this;
    }

    public function getAdrVille(): ?string
    {
        return $this->adr_ville;
    }

    public function setAdrVille(string $adr_ville): static
    {
        $this->adr_ville = $adr_ville;

        return $this;
    }

    public function getAdrPays(): ?string
    {
        return $this->adr_pays;
    }

    public function setAdrPays(string $adr_pays): static
    {
        $this->adr_pays = $adr_pays;

        return $this;
    }
}

src/Form/AdresseType.php
<?php

namespace App\Form;

use App\Entity\Adresse;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdresseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('adr_nom')
            ->add('adr_prenom')
            ->add('adr_rue')
            ->add('adr_code_postal')
            ->add('adr_telephone')
            ->add('adr_ville')
            ->add('adr_pays')
            //->add('adr_uti')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Adresse::class,
        ]);
    }
}

src/Controller/AdresseController.php
<?php

namespace App\Controller;

use App\Entity\Adresse;
use App\Form\AdresseType;
use App\Repository\AdresseRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/adresse')]
class AdresseController extends AbstractController
{
    #[Route('/', name: 'app_adresse_index', methods: ['GET'])]
    public function index(AdresseRepository $adresseRepository): Response
    {
        return $this->render('adresse/index.html.twig', [
            'adresses' => $adresseRepository->findAll(),
        ]);
    }

    #[Route('/mesAdresse', name: 'app_adresse_mon_index', methods: ['GET'])]
    public function monIndex(AdresseRepository $adresseRepository): Response
    {
        return $this->render('adresse/index.html.twig', [
            'adresses' => $adresseRepository->findBy(['adr_uti' => $this->getUser()])
        ]);
    }

    #[Route('/new', name: 'app_adresse_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $adresse = new Adresse();
        $form = $this->createForm(AdresseType::class, $adresse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $adresse->setAdrUti($this->getUser());
            $entityManager->persist($adresse);
            $entityManager->flush();

            return $this->redirectToRoute('app_adresse_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('adresse/new.html.twig', [
            'adresse' => $adresse,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_adresse_show', methods: ['GET'])]
    public function show(Adresse $adresse): Response
    {
        return $this->render('adresse/show.html.twig', [
            'adresse' => $adresse,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_adresse_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Adresse $adresse, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AdresseType::class, $adresse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_adresse_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('adresse/edit.html.twig', [
            'adresse' => $adresse,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_adresse_delete', methods: ['POST'])]
    public function delete(Request $request, Adresse $adresse, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$adresse->getId(), $request->request->get('_token'))) {
            $entityManager->remove($adresse);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_adresse_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/adresse/_delete_form.html.twig
<form method="post" action="{{ path('app_adresse_delete', {'id': adresse.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ adresse.id) }}">
    <button class="btn">Delete</button>
</form>

templates/adresse/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Adresse{% endblock %}

{% block body %}
    <h1>Edit Adresse</h1>

    {{ include('adresse/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_adresse_index') }}">back to list</a>

    {{ include('adresse/_delete_form.html.twig') }}
{% endblock %}

templates/adresse/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adresse index{% endblock %}

{% block body %}
    <h1>Adresse index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Adr_nom</th>
                <th>Ard_prenom</th>
                <th>Adr_rue</th>
                <th>Adr_code_postal</th>
                <th>Adr_telephone</th>
                <th>Adr_ville</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for adresse in adresses %}
            <tr>
                <td>{{ adresse.id }}</td>
                <td>{{ adresse.adrNom }}</td>
                <td>{{ adresse.adrPrenom }}</td>
                <td>{{ adresse.adrRue }}</td>
                <td>{{ adresse.adrCodePostal }}</td>
                <td>{{ adresse.adrTelephone }}</td>
                <td>{{ adresse.adrVille }}</td>
                <td>
                    <a href="{{ path('app_adresse_show', {'id': adresse.id}) }}">show</a>
                    <a href="{{ path('app_adresse_edit', {'id': adresse.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_adresse_new') }}">Create new</a>
{% endblock %}

templates/adresse/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Adresse{% endblock %}

{% block body %}
    <h1>Create new Adresse</h1>

    {{ include('adresse/_form.html.twig') }}

    <a href="{{ path('app_adresse_index') }}">back to list</a>
{% endblock %}

templates/adresse/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adresse{% endblock %}

{% block body %}
    <h1>Adresse</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ adresse.id }}</td>
            </tr>
            <tr>
                <th>Adr_nom</th>
                <td>{{ adresse.adrNom }}</td>
            </tr>
            <tr>
                <th>Ard_prenom</th>
                <td>{{ adresse.ardPrenom }}</td>
            </tr>
            <tr>
                <th>Adr_rue</th>
                <td>{{ adresse.adrRue }}</td>
            </tr>
            <tr>
                <th>Adr_code_postal</th>
                <td>{{ adresse.adrCodePostal }}</td>
            </tr>
            <tr>
                <th>Adr_telephone</th>
                <td>{{ adresse.adrTelephone }}</td>
            </tr>
            <tr>
                <th>Adr_ville</th>
                <td>{{ adresse.adrVille }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_adresse_index') }}">back to list</a>

    <a href="{{ path('app_adresse_edit', {'id': adresse.id}) }}">edit</a>

    {{ include('adresse/_delete_form.html.twig') }}
{% endblock %}