src/Entity/Produit.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Metadata\ApiResource;
use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[ApiResource(
    normalizationContext: [ "groups" => ["read:product"]]
)]
#[Vich\Uploadable]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(["read:product"])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(["read:product"])]
    private ?string $pro_nom = null;

        // NOTE: This is not a mapped field of entity metadata, just a simple property.
        #[Vich\UploadableField(mapping: 'produit_images', fileNameProperty: 'pro_image')]
        private ?File $imageFile = null;
    
        // #[ORM\Column(nullable: true)]
        // private ?string $imageName = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 9, scale: 2, nullable: true)]
    #[Groups(["read:product"])]
    private ?string $pro_prix = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(["read:product"])]
    private ?string $pro_image = null;

    #[ORM\Column( nullable: true, type:Types::TEXT)]
    private ?string $pro_description = null;

    #[ORM\Column(nullable: true)]
    private ?int $pro_stkphy = null;

    #[ORM\Column(nullable: true)]
    private ?int $pro_stkale = null;

    #[ORM\ManyToOne(inversedBy: 'produits', targetEntity: Categorie::class)]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(["read:product"])]
    private ?categorie $cat = null;

    #[ORM\OneToMany(mappedBy: 'pro', targetEntity: Vente::class)]
    private Collection $ventes;

    #[ORM\OneToMany(mappedBy: 'pan_pro', targetEntity: Panier::class)]
    private Collection $paniers;

    #[ORM\OneToMany(mappedBy: 'liv_pro', targetEntity: Livraison::class)]
    private Collection $livraisons;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $pro_updateAt = null;

    public function __construct()
    {
        $this->ventes = new ArrayCollection();
        $this->paniers = new ArrayCollection();
        $this->livraisons = new ArrayCollection();
        $this->pro_updateAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProNom(): ?string
    {
        return $this->pro_nom;
    }

    public function setProNom(string $pro_nom): static
    {
        $this->pro_nom = $pro_nom;

        return $this;
    }

     /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->pro_updateAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    // public function setImageName(?string $imageName): void
    // {
    //     $this->imageName = $imageName;
    // }

    // public function getImageName(): ?string
    // {
    //     return $this->imageName;
    // }

    public function getProPrix(): ?string
    {
        return $this->pro_prix;
    }

    public function setProPrix(?string $pro_prix): static
    {
        $this->pro_prix = $pro_prix;

        return $this;
    }

    public function getProImage(): ?string
    {
        return $this->pro_image;
    }

    public function setProImage(?string $pro_image): static
    {
        $this->pro_image = $pro_image;

        return $this;
    }

    public function getProDescription(): ?string
    {
        return $this->pro_description;
    }

    public function setProDescription(?string $pro_description): static
    {
        $this->pro_description = $pro_description;

        return $this;
    }

    public function getProStkphy(): ?int
    {
        return $this->pro_stkphy;
    }

    public function setProStkphy(?int $pro_stkphy): static
    {
        $this->pro_stkphy = $pro_stkphy;

        return $this;
    }

    public function getProStkale(): ?int
    {
        return $this->pro_stkale;
    }

    public function setProStkale(?int $pro_stkale): static
    {
        $this->pro_stkale = $pro_stkale;

        return $this;
    }

    public function getCat(): ?categorie
    {
        return $this->cat;
    }

    public function setCat(?categorie $cat): static
    {
        $this->cat = $cat;

        return $this;
    }

    /**
     * @return Collection<int, Vente>
     */
    public function getVentes(): Collection
    {
        return $this->ventes;
    }

    public function addVente(Vente $vente): static
    {
        if (!$this->ventes->contains($vente)) {
            $this->ventes->add($vente);
            $vente->setPro($this);
        }

        return $this;
    }

    public function removeVente(Vente $vente): static
    {
        if ($this->ventes->removeElement($vente)) {
            // set the owning side to null (unless already changed)
            if ($vente->getPro() === $this) {
                $vente->setPro(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Panier>
     */
    public function getPaniers(): Collection
    {
        return $this->paniers;
    }

    public function addPanier(Panier $panier): static
    {
        if (!$this->paniers->contains($panier)) {
            $this->paniers->add($panier);
            $panier->setPanPro($this);
        }

        return $this;
    }

    public function removePanier(Panier $panier): static
    {
        if ($this->paniers->removeElement($panier)) {
            // set the owning side to null (unless already changed)
            if ($panier->getPanPro() === $this) {
                $panier->setPanPro(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Livraison>
     */
    public function getLivraisons(): Collection
    {
        return $this->livraisons;
    }

    public function addLivraison(Livraison $livraison): static
    {
        if (!$this->livraisons->contains($livraison)) {
            $this->livraisons->add($livraison);
            $livraison->setLivPro($this);
        }

        return $this;
    }

    public function removeLivraison(Livraison $livraison): static
    {
        if ($this->livraisons->removeElement($livraison)) {
            // set the owning side to null (unless already changed)
            if ($livraison->getLivPro() === $this) {
                $livraison->setLivPro(null);
            }
        }

        return $this;
    }

    public function getProUpdateAt(): ?\DateTimeImmutable
    {
        return $this->pro_updateAt;
    }

    #[ORM\PrePersist]
    public function setProUpdateAt(): static
    {
        $this->pro_updateAt = new \DateTimeImmutable();

        return $this;
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use App\Repository\CategorieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/article')]
class ArticleController extends AbstractController
{
    #[Route('/', name: 'app_article_index', methods: ['GET'])]
    public function index(ProduitRepository $produitRepository): Response
    {
        return $this->render('article/index.html.twig', [
            'produits' => $produitRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_article_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager,CategorieRepository $categorieRepository): Response
    {
        //$cat =  $categorieRepository->findBy(['cat_parent'=> !null]);
        $cat =  $categorieRepository->findSousCat();
        //$cat =  $categorieRepository->findCatSql();
       // dd($cat);
        $produit = new Produit();
        // $form = $this->createForm(ProduitType::class, $produit);
        $form = $this->createForm(ProduitType::class, $produit, options: [
            'sousCat' =>  $cat
        ]);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($produit);
            $entityManager->flush();

            return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('article/new.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_article_show', methods: ['GET'])]
    public function show(Produit $produit): Response
    {
        return $this->render('article/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_article_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Produit $produit, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('article/edit.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_article_delete', methods: ['POST'])]
    public function delete(Request $request, Produit $produit, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->request->get('_token'))) {
            $entityManager->remove($produit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('app_article_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn">Delete</button>
</form>

templates/article/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Produit{% endblock %}

{% block body %}
    <h1>Edit Produit</h1>

    {{ include('article/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_article_index') }}">back to list</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit index{% endblock %}

{% block body %}
    <h1>Produit index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Pro_nom</th>
                <th>Pro_prix</th>
                <th>Pro_image</th>
                <th>Pro_description</th>
                <th>Pro_stkphy</th>
                <th>Pro_stkale</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for produit in produits %}
            <tr>
                <td>{{ produit.id }}</td>
                <td>{{ produit.proNom }}</td>
                <td>{{ produit.proPrix }}</td>
                <td>{{ produit.proImage }}</td>
                <td>{{ produit.proDescription }}</td>
                <td>{{ produit.proStkphy }}</td>
                <td>{{ produit.proStkale }}</td>
                <td>
                    <a href="{{ path('app_article_show', {'id': produit.id}) }}">show</a>
                    <a href="{{ path('app_article_edit', {'id': produit.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_article_new') }}">Create new</a>
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Produit{% endblock %}

{% block body %}
    <h1>Create new Produit</h1>

    {{ include('article/_form.html.twig') }}

    <a href="{{ path('app_article_index') }}">back to list</a>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}
    <h1>Produit</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ produit.id }}</td>
            </tr>
            <tr>
                <th>Pro_nom</th>
                <td>{{ produit.proNom }}</td>
            </tr>
            <tr>
                <th>Pro_prix</th>
                <td>{{ produit.proPrix }}</td>
            </tr>
            <tr>
                <th>Pro_image</th>
                <td>{{ produit.proImage }}</td>
            </tr>
            <tr>
                <th>Pro_description</th>
                <td>{{ produit.proDescription }}</td>
            </tr>
            <tr>
                <th>Pro_stkphy</th>
                <td>{{ produit.proStkphy }}</td>
            </tr>
            <tr>
                <th>Pro_stkale</th>
                <td>{{ produit.proStkale }}</td>
            </tr>
            <tr>
                <img style="max-width: 500px;" src="{{ vich_uploader_asset(produit, 'imageFile') }}">
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_article_index') }}">back to list</a>

    <a href="{{ path('app_article_edit', {'id': produit.id}) }}">edit</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}